version: "3.7"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    expose:
      - "2181"
    ports:
      - 2181:2181
           
  kafka-1:
    image: wurstmeister/kafka
    container_name: kafka-1
    command: [start-kafka.sh]
    expose:
      - "8080"
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka-1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      
    depends_on:
      - "zookeeper"

  kafka-2:
    image: wurstmeister/kafka
    container_name: kafka-2
    command: [start-kafka.sh]
    expose:
      - "8080"
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka-2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      
    depends_on:
      - "zookeeper"
      
  pyspark:
    image: ba74ec4dfd45
    container_name: pyspark-notebook
    ports:
      - "8888:8888"
    depends_on:
      - "kafka-1"
      - "kafka-2"            
    links:
      - kafka-1
      - kafka-2
    volumes:
      - ./notebook/:/home/jovyan/work/
      
  spark-master:
    image: aaa3e3ca21bc
    container_name: spark-master
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
    environment:
      - SPARK_LOCAL_IP=spark-master
      
  spark-master:
    image: 4bf7e8f30c9c
    hostname: spark-master
    container_name: spark-master
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
    environment:
      - SPARK_LOCAL_IP=spark-master
      
  spark-worker-1:
    image: 11393bee140a
    hostname: spark-worker-1
    container_name: spark-worker-1
    ports:
      - "8081:8081"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=128m
      - SPARK_EXECUTOR_MEMORY=256m
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
       
  spark-worker-2:
    image: 11393bee140a
    hostname: spark-worker-2
    container_name: spark-worker-2
    ports:
      - "8082:8081"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=128m
      - SPARK_EXECUTOR_MEMORY=256m
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data

  kafka_manager:
    image: hlebalbau/kafka-manager:1.3.3.18
    container_name: kafka_manager
    expose:
      - "9000"
    ports:
      - 9000:9000
    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: "random-secret"
      command: -Dpidfile.path=/dev/null
    links:
        - kafka-1
        - kafka-2
        - zookeeper
    depends_on:
        - "zookeeper"
        - "kafka-1"
        - "kafka-2"
            
